### ISSUE TITLE
bug(util): color not updating in labels

### ISSUE THREAD

**Issue by TGTGamer** [Videndum/action-masterminds#166]
> Color doesn't work at all actually (Except documentation is generated)
> ![image](https://user-images.githubusercontent.com/11695769/126722261-28c06ccb-e37a-447e-9262-7e8dfc71ae9d.png)
> config has the attribute in the following format: `"color": "3ea2e6"`
> 
> _Originally posted by @Netail in https://github.com/Videndum/action-masterminds/discussions/165#discussioncomment-1039939_

Heya @Netail, to help me identify and fix this issue, could you provide the following? 

**Console Logs**
Please [set the `ACTIONS_RUNNER_DEBUG` secret to `true` to enable debug logging](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging), rerun the labeler workflow

**Labels Config**
Please could you upload a git or attach a copy of how you have your labels configured. This can either be just the label section or the entire config file depending on how large it is.

**Comment by Netail** [comment]
https://gist.github.com/Netail/65643561e214df2de89a0773a88469f1

**Comment by Netail** [comment]
Test Repo: https://github.com/Netail/test
See PR and PR content. (bug and documentation still have old color and DevOps no color at all)

**Comment by TGTGamer** [comment]
Thank you for confirming this bug. I'm going to start working on it now so bare with as it's like 01:30 here and i've not touched this code in a short while.

**Comment by Netail** [comment]
2:37 here :P

**Comment by TGTGamer** [comment]
@Netail really sorry for the delayed response, the migraine ate away my weekend pretty quickly. 

So I have found the issue, and am working on a patch right now. Should be live within the next hour. 

I can confirm that the `@videndum/release-mastermind` has a working release as of current.

**Comment by TGTGamer** [comment]
Fixed in latest version. 2.1.3 `@videndum/label-mastermind` or current on `@videndum/action-mastermind`
